title: Mineralogy Extension
stadocgen-path: /minext
acronym: MinExt
documentation-landing-page: https://mineralogy.tdwg.org
github-repo: https://github.com/tdwg/mineralogy
source-data-files:
source-md-files:
last-modified: 20250419
comments:
status: Draft